"""Deterministic recipe for Android map/location address forms.

This is not a general Kotlin generator. It is a task-family recipe for the
repeated P69-19 shape: Compose address/signup forms need an OSMDroid map tap
that reverse-geocodes into existing address state and persists coordinates in
the existing Firebase payload.

The goal is to keep runtime small and remove the brittle part from the model:
MapEventsOverlay/coroutine/geocoder structure is generated by the harness, while
the planner still decides whether the android_map_location family applies.
"""
from __future__ import annotations

import difflib
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from app.services.structural_edit import validate_kotlin_structure


ANDROID_MAP_LOCATION_CONTRACTS = [
    "map_ui_present",
    "user_can_select_location",
    "location_updates_form_state",
    "persisted_to_storage",
    "installed_library_only",
    "geocoder_lifecycle_safe",
]


@dataclass
class AndroidMapLocationRecipeResult:
    content: str
    diff: str
    files_changed: list[str]
    summary: str
    applied_operations: list[str] = field(default_factory=list)
    contract_coverage: dict[str, Any] | None = None


def try_generate_android_map_location_recipe(
    *,
    file_path: str,
    original_content: str,
    plan_json: dict[str, Any] | None = None,
    task_description: str = "",
) -> AndroidMapLocationRecipeResult | None:
    """Generate a small deterministic patch for the map/location task family.

    Returns None when the plan/file is outside the supported shape so the
    normal codegen path can continue.
    """
    if Path(file_path).suffix.lower() not in {".kt", ".kts"}:
        return None
    if not original_content.strip() or "@Composable" not in original_content:
        return None
    if not _is_android_map_location_task(plan_json or {}, task_description):
        return None
    if not _looks_like_address_form(file_path, original_content):
        return None

    content = original_content
    applied: list[str] = []
    had_map_ui = _has_map_ui(content)
    had_geocoder_locale = bool(re.search(r"Geocoder\s*\([^,)]+,\s*Locale", content))
    had_persisted_coords = _has_persisted_coordinates(content)

    for import_line in _needed_imports(content):
        before = content
        content = _add_import(content, import_line)
        if content != before:
            applied.append(f"add_import:{import_line.removeprefix('import ')}")

    before = content
    content = _ensure_address_state(content)
    if content != before:
        applied.append("ensure_address_state")

    before = content
    content = _ensure_geocoder_locale(content)
    if content != before:
        applied.append("ensure_geocoder_locale")

    if not _has_map_ui(content):
        before = content
        content = _ensure_map_helpers(content)
        if content != before:
            applied.append("ensure_map_geocode_helpers")

    if not _has_map_ui(content):
        before = content
        content = _insert_map_picker(content)
        if content != before:
            applied.append("insert_osmdroid_map_picker")

    before = content
    content = _wire_payload_fields(content)
    if content != before:
        applied.append("wire_address_payload")

    if content == original_content:
        return None

    structure_errors = validate_kotlin_structure(content)
    if structure_errors:
        return None

    diff = _unified_diff(file_path, original_content, content)
    if not diff.strip():
        return None

    return AndroidMapLocationRecipeResult(
        content=content,
        diff=diff,
        files_changed=[file_path],
        summary="Generated Android map/location address patch via harness recipe",
        applied_operations=applied,
        contract_coverage=_coverage_payload(
            file_path=file_path,
            had_map_ui=had_map_ui,
            had_geocoder_locale=had_geocoder_locale,
            had_persisted_coords=had_persisted_coords,
        ),
    )


def _is_android_map_location_task(plan_json: dict[str, Any], task_description: str) -> bool:
    domain = str(plan_json.get("domain_playbook_id") or plan_json.get("domain_id") or "")
    if domain == "android_map_location":
        return True
    contract_ids = {
        str(c.get("contract_id") or c.get("id") or "")
        for c in (plan_json.get("required_contracts") or [])
        if isinstance(c, dict)
    }
    if {"map_ui_present", "user_can_select_location"} & contract_ids:
        return True
    text = " ".join(
        str(v or "")
        for v in (
            plan_json.get("objective"),
            plan_json.get("change_summary"),
            plan_json.get("change_explanation"),
            task_description,
        )
    ).lower()
    return ("map" in text or "osmdroid" in text) and (
        "address" in text or "location" in text or "geocode" in text
    )


def _looks_like_address_form(file_path: str, content: str) -> bool:
    path = file_path.replace("\\", "/").lower()
    if any(name in path for name in ("signup.kt", "kycaddressform.kt")):
        return True
    return (
        "FirebaseDatabase" in content
        and "mapOf(" in content
        and any(key in content for key in ('"street"', '"city"', '"houseNumber"'))
    )


def _has_map_ui(content: str) -> bool:
    return (
        "MapEventsOverlay" in content
        and "singleTapConfirmedHelper" in content
        and "MapView" in content
    )


def _has_persisted_coordinates(content: str) -> bool:
    return bool(re.search(r'"latitude"\s+to\s+(?!0(?:\.0)?\b)', content)) and bool(
        re.search(r'"longitude"\s+to\s+(?!0(?:\.0)?\b)', content)
    )


def _needed_imports(content: str) -> list[str]:
    imports = ["import android.location.Geocoder"]
    if not _has_map_ui(content):
        imports.extend(
            [
                "import android.util.Log",
                "import androidx.compose.runtime.DisposableEffect",
                "import androidx.compose.ui.viewinterop.AndroidView",
                "import kotlinx.coroutines.Dispatchers",
                "import kotlinx.coroutines.launch",
                "import kotlinx.coroutines.withContext",
                "import org.osmdroid.events.MapEventsReceiver",
                "import org.osmdroid.tileprovider.tilesource.TileSourceFactory",
                "import org.osmdroid.util.GeoPoint",
                "import org.osmdroid.views.MapView",
                "import org.osmdroid.views.overlay.MapEventsOverlay",
                "import org.osmdroid.views.overlay.Marker",
            ]
        )
    if not re.search(r"^\s*import\s+java\.util\.(?:Locale|\*)\s*$", content, re.MULTILINE):
        imports.append("import java.util.Locale")
    return imports


def _add_import(content: str, import_line: str) -> str:
    lines = content.splitlines()
    if any(line.strip() == import_line for line in lines):
        return content
    if import_line == "import java.util.Locale" and any(
        re.match(r"^\s*import\s+java\.util\.\*\s*$", line) for line in lines
    ):
        return content

    insert_at = 0
    for idx, line in enumerate(lines):
        text = line.strip()
        if text.startswith("package ") or text.startswith("import "):
            insert_at = idx + 1
            continue
        if insert_at and text:
            break
    new_lines = lines[:insert_at] + [import_line] + lines[insert_at:]
    return _join_like(content, new_lines)


def _ensure_address_state(content: str) -> str:
    names = _field_names(content)
    needed = []
    for var_name, default in (
        ("houseNumber", '""'),
        ("street", '""'),
        ("area", '""'),
        (names["post_code"], '""'),
        ("division", '""'),
        ("district", '""'),
        ("thana", '""'),
        ("city", '""'),
        ("country", '"Bangladesh"'),
        (names["notes"], '""'),
        ("latitude", "0.0"),
        ("longitude", "0.0"),
    ):
        if not re.search(rf"\bvar\s+{re.escape(var_name)}\s+by\s+remember\b", content):
            needed.append(f"    var {var_name} by remember {{ mutableStateOf({default}) }}")
    needs_map_ref = (not _has_map_ui(content)) or "mapViewRef" in content
    if needs_map_ref and not re.search(r"\bvar\s+mapViewRef\s+by\s+remember\s*\{", content):
        needed.append("    var mapViewRef by remember { mutableStateOf<MapView?>(null) }")
    if not re.search(r"\bval\s+coroutineScope\s*=\s*rememberCoroutineScope\(\)", content):
        needed.append("    val coroutineScope = rememberCoroutineScope()")
    if needs_map_ref and "DisposableEffect(mapViewRef)" not in content:
        needed.extend(
            [
                "    DisposableEffect(mapViewRef) {",
                "        onDispose {",
                "            mapViewRef?.onPause()",
                "            mapViewRef?.onDetach()",
                "            mapViewRef = null",
                "        }",
                "    }",
            ]
        )
    if not needed:
        return content

    lines = content.splitlines()
    insert_after = _last_state_line(lines)
    if insert_after <= 0:
        insert_after = _first_composable_body_line(lines)
    if insert_after <= 0:
        return content
    new_lines = lines[:insert_after] + needed + lines[insert_after:]
    return _join_like(content, new_lines)


def _field_names(content: str) -> dict[str, str]:
    return {
        "post_code": "postCode"
        if re.search(r"\b(?:var|val)\s+postCode\b", content)
        else "postcode",
        "notes": "note" if re.search(r"\b(?:var|val)\s+note\b", content) else "notes",
    }


def _last_state_line(lines: list[str]) -> int:
    last = 0
    state_re = re.compile(r"^\s*var\s+\w+\s+by\s+remember\s*\{")
    for idx, line in enumerate(lines, start=1):
        if state_re.search(line):
            last = idx
    return last


def _first_composable_body_line(lines: list[str]) -> int:
    for idx, line in enumerate(lines, start=1):
        if line.strip().startswith("fun ") and "{" in line:
            return idx
    return 0


def _ensure_geocoder_locale(content: str) -> str:
    return re.sub(
        r"Geocoder\((context|ctx)\)",
        r"Geocoder(\1, Locale.getDefault())",
        content,
    )


def _ensure_map_helpers(content: str) -> str:
    if "fun reverseGeocodeAddress(" in content and "fun locateManualAddress(" in content:
        return content
    names = _field_names(content)
    helper = _map_helper_block(post_code=names["post_code"])
    lines = content.splitlines()
    insert_after = _coroutine_scope_line(lines)
    if insert_after <= 0:
        insert_after = _last_state_line(lines)
    if insert_after <= 0:
        return content
    new_lines = lines[:insert_after] + [""] + helper.splitlines() + lines[insert_after:]
    return _join_like(content, new_lines)


def _coroutine_scope_line(lines: list[str]) -> int:
    for idx, line in enumerate(lines, start=1):
        if re.search(r"\bval\s+coroutineScope\s*=\s*rememberCoroutineScope\(\)", line):
            return idx
    return 0


def _map_helper_block(*, post_code: str) -> str:
    return f"""    fun reverseGeocodeAddress(point: GeoPoint, marker: Marker, map: MapView) {{
        latitude = point.latitude
        longitude = point.longitude
        marker.position = point
        marker.title = "Selected address"
        map.invalidate()
        coroutineScope.launch {{
            try {{
                val addresses = withContext(Dispatchers.IO) {{
                    Geocoder(map.context, Locale.getDefault())
                        .getFromLocation(point.latitude, point.longitude, 1)
                }}
                addresses?.firstOrNull()?.let {{ addr ->
                    houseNumber = addr.subThoroughfare ?: houseNumber
                    street = addr.thoroughfare ?: street
                    area = addr.subLocality ?: area
                    division = addr.adminArea ?: division
                    district = addr.subAdminArea ?: district
                    thana = addr.locality ?: thana
                    city = addr.locality ?: city
                    country = addr.countryName ?: country
                    {post_code} = addr.postalCode ?: {post_code}
                }}
            }} catch (e: Exception) {{
                Log.e("MapPicker", "Reverse geocoding failed", e)
            }}
        }}
    }}

    fun locateManualAddress(map: MapView) {{
        val query = listOf(houseNumber, street, area, city, country)
            .map {{ it.trim() }}
            .filter {{ it.isNotBlank() }}
            .joinToString(", ")
        if (query.isBlank()) return
        coroutineScope.launch {{
            try {{
                val results = withContext(Dispatchers.IO) {{
                    Geocoder(map.context, Locale.getDefault())
                        .getFromLocationName(query, 1)
                }}
                results?.firstOrNull()?.let {{ addr ->
                    latitude = addr.latitude
                    longitude = addr.longitude
                    val point = GeoPoint(latitude, longitude)
                    val marker = map.overlays.filterIsInstance<Marker>().firstOrNull()
                        ?: Marker(map).also {{
                            it.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM)
                            map.overlays.add(it)
                        }}
                    marker.position = point
                    marker.title = "Selected address"
                    map.controller.animateTo(point)
                    map.controller.setZoom(16.0)
                    map.invalidate()
                    reverseGeocodeAddress(point, marker, map)
                }}
            }} catch (e: Exception) {{
                Log.e("MapPicker", "Forward geocoding failed", e)
            }}
        }}
    }}

"""


def _insert_map_picker(content: str) -> str:
    names = _field_names(content)
    block = _map_picker_block(
        post_code=names["post_code"],
        notes=names["notes"],
        include_manual_fields=not _has_manual_address_inputs(content),
    )
    lines = content.splitlines()
    insert_at = _submit_button_line(lines)
    if insert_at <= 0:
        return content
    new_lines = lines[: insert_at - 1] + block.splitlines() + [""] + lines[insert_at - 1 :]
    return _join_like(content, new_lines)


def _has_manual_address_inputs(content: str) -> bool:
    return bool(
        re.search(r"OutlinedTextField\s*\([^)]*value\s*=\s*houseNumber", content, re.DOTALL)
        and re.search(r"OutlinedTextField\s*\([^)]*value\s*=\s*street", content, re.DOTALL)
    )


def _submit_button_line(lines: list[str]) -> int:
    button_lines: list[int] = []
    for idx, line in enumerate(lines, start=1):
        if re.match(r"^\s{8}Button\s*\(\s*$", line):
            button_lines.append(idx)
    return button_lines[-1] if button_lines else 0


def _map_picker_block(*, post_code: str, notes: str, include_manual_fields: bool) -> str:
    manual_fields = (
        f"""        Spacer(modifier = Modifier.height(16.dp))
        Text("Address details", fontSize = 16.sp, fontWeight = FontWeight.SemiBold)
        OutlinedTextField(
            value = houseNumber,
            onValueChange = {{ houseNumber = it }},
            label = {{ Text("House number") }},
            modifier = Modifier.fillMaxWidth()
        )
        OutlinedTextField(
            value = street,
            onValueChange = {{ street = it }},
            label = {{ Text("Street") }},
            modifier = Modifier.fillMaxWidth()
        )
        OutlinedTextField(
            value = area,
            onValueChange = {{ area = it }},
            label = {{ Text("Area") }},
            modifier = Modifier.fillMaxWidth()
        )
        OutlinedTextField(
            value = city,
            onValueChange = {{ city = it }},
            label = {{ Text("City") }},
            modifier = Modifier.fillMaxWidth()
        )
        OutlinedTextField(
            value = country,
            onValueChange = {{ country = it }},
            label = {{ Text("Country") }},
            modifier = Modifier.fillMaxWidth()
        )
        OutlinedTextField(
            value = {post_code},
            onValueChange = {{ {post_code} = it }},
            label = {{ Text("Postcode") }},
            modifier = Modifier.fillMaxWidth()
        )
        OutlinedTextField(
            value = {notes},
            onValueChange = {{ {notes} = it }},
            label = {{ Text("Notes") }},
            modifier = Modifier.fillMaxWidth()
        )
        TextButton(onClick = {{ mapViewRef?.let {{ locateManualAddress(it) }} }}) {{
            Text("Find typed address on map")
        }}
"""
        if include_manual_fields
        else """        Spacer(modifier = Modifier.height(16.dp))
        TextButton(onClick = { mapViewRef?.let { locateManualAddress(it) } }) {
            Text("Find typed address on map")
        }
"""
    )
    return f"""{manual_fields}
        Spacer(modifier = Modifier.height(16.dp))
        Text("Select address on map", fontSize = 16.sp, fontWeight = FontWeight.SemiBold)
        AndroidView(
            factory = {{ ctx ->
                MapView(ctx).apply {{
                    mapViewRef = this
                    setTileSource(TileSourceFactory.MAPNIK)
                    setMultiTouchControls(true)
                    controller.setZoom(14.0)
                    val startPoint = GeoPoint(
                        if (latitude != 0.0) latitude else 23.6850,
                        if (longitude != 0.0) longitude else 90.3563
                    )
                    controller.setCenter(startPoint)
                    val marker = Marker(this@apply).apply {{
                        position = startPoint
                        setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM)
                    }}
                    overlays.add(marker)
                    overlays.add(MapEventsOverlay(object : MapEventsReceiver {{
                        override fun singleTapConfirmedHelper(p: GeoPoint?): Boolean {{
                            val point = p ?: return false
                            reverseGeocodeAddress(point, marker, this@apply)
                            return true
                        }}

                        override fun longPressHelper(p: GeoPoint?): Boolean = false
                    }}))
                }}
            }},
            modifier = Modifier
                .fillMaxWidth()
                .height(220.dp)
        )
        Text(
            text = if (latitude != 0.0) "Pinned: ${{String.format("%.4f", latitude)}}, ${{String.format("%.4f", longitude)}}" else "Tap the map to pin your address",
            fontSize = 12.sp,
            color = if (latitude != 0.0) Color(0xFF2F3367) else Color.Gray
        )
"""


def _wire_payload_fields(content: str) -> str:
    names = _field_names(content)
    replacements = {
        "houseNumber": "houseNumber",
        "street": "street",
        "area": "area",
        "division": "division",
        "district": "district",
        "thana": "thana",
        "city": "city",
        "country": "country",
        "postcode": names["post_code"],
        "postCode": names["post_code"],
        "notes": names["notes"],
    }
    new_content = content
    for key, var_name in replacements.items():
        new_content = re.sub(
            rf'("{re.escape(key)}"\s+to\s+)""',
            rf"\1{var_name}",
            new_content,
        )
    new_content = re.sub(r'("latitude"\s+to\s+)0(?:\.0)?\b', r"\1latitude", new_content)
    new_content = re.sub(r'("longitude"\s+to\s+)0(?:\.0)?\b', r"\1longitude", new_content)
    new_content = _ensure_payload_entry(new_content, "latitude", "latitude")
    new_content = _ensure_payload_entry(new_content, "longitude", "longitude")
    return new_content


def _ensure_payload_entry(content: str, key: str, var_name: str) -> str:
    if re.search(rf'"{re.escape(key)}"\s+to\s+', content):
        return content
    lines = content.splitlines()
    map_ranges = _mapof_ranges(lines)
    for start, end in map_ranges:
        for idx in range(start, end):
            if re.search(r'"notes"\s+to\s+|\bnotes\s*=', lines[idx]):
                indent = re.match(r"^(\s*)", lines[idx]).group(1)  # type: ignore[union-attr]
                if not lines[idx].rstrip().endswith(","):
                    lines[idx] = lines[idx].rstrip() + ","
                lines.insert(idx + 1, f'{indent}"{key}" to {var_name},')
                return _join_like(content, lines)
    return content


def _mapof_ranges(lines: list[str]) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    for idx, line in enumerate(lines):
        if "mapOf(" not in line:
            continue
        balance = 0
        seen = False
        for end in range(idx, len(lines)):
            for ch in lines[end]:
                if ch == "(":
                    balance += 1
                    seen = True
                elif ch == ")":
                    balance -= 1
            if seen and balance <= 0:
                ranges.append((idx, end + 1))
                break
    return ranges


def _coverage_payload(
    *,
    file_path: str,
    had_map_ui: bool,
    had_geocoder_locale: bool,
    had_persisted_coords: bool,
) -> dict[str, Any]:
    implemented: list[dict[str, str]] = []
    no_change: list[dict[str, str]] = []

    def add(cid: str, *, already: bool, quote: str) -> None:
        row = {
            "contract_id": cid,
            "file_path": file_path,
            "evidence_quote": quote,
            "evidence_mode": "preexisting" if already else "recipe_diff",
        }
        if already:
            no_change.append(row)
        else:
            implemented.append(row)

    add("map_ui_present", already=had_map_ui, quote="MapEventsOverlay")
    add("user_can_select_location", already=had_map_ui, quote="singleTapConfirmedHelper")
    add("location_updates_form_state", already=had_map_ui, quote="getFromLocation")
    add("persisted_to_storage", already=had_persisted_coords, quote='"latitude" to latitude')
    add("installed_library_only", already=had_map_ui, quote="org.osmdroid.")
    add(
        "geocoder_lifecycle_safe",
        already=had_geocoder_locale,
        quote="Geocoder(ctx, Locale.getDefault())",
    )
    return {
        "implemented_contracts": implemented,
        "verified_no_change_contracts": no_change,
        "unimplemented_contracts": [],
    }


def _join_like(original: str, lines: list[str]) -> str:
    text = "\n".join(lines)
    return text + ("\n" if original.endswith("\n") else "")


def _unified_diff(path: str, before: str, after: str) -> str:
    before_lines = before.splitlines(keepends=True)
    after_lines = after.splitlines(keepends=True)
    body = "".join(
        difflib.unified_diff(
            before_lines,
            after_lines,
            fromfile=f"a/{path}",
            tofile=f"b/{path}",
            n=3,
        )
    )
    return f"diff --git a/{path} b/{path}\n{body}" if body else ""
